default:
  image: node:18.17.0

stages:
  - build
  - test
  - deploy

cache:
  - &global_cache_node_mods
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
    policy: pull

install:
  stage: .pre # always first, no matter if it is listed in stages
  cache:
    # Mimic &global_cache_node_mods config but override policy
    # to allow this job to update the cache at the end of the job
    # and only update if it was a successful job (#5)
    - <<: *global_cache_node_mods
      when: on_success
      policy: pull-push
  script:
    # define cache dir & use it npm!
    - npm ci --cache .npm --prefer-offline

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  needs:
    - job: build
      artifacts: true
  script:
    - npm run test

deploy_production:
  stage: deploy
  only:
    - main
  needs:
    - job: build
      artifacts: true
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
